### ISSUE TITLE
Error when action is present

### ISSUE THREAD

**Issue by BriceRenaudeau** [kiwicampus/ros2_graph#28]
When even I launch ros2_graph on a node that sends a goal to an action, the process crashes:
```bash
$ros2_graph /simple_move

Invalid topic name: topic name must not contain repeated '/':
  '//simple_move'
    ^
Traceback (most recent call last):
  File "/usr/local/bin/ros2_graph", line 8, in <module>
    sys.exit(__main__.main())
  File "/usr/local/lib/python3.10/dist-packages/ros2_graph/__main__.py", line 194, in main
    graph_generator.get_node_graph(node)
  File "/usr/local/lib/python3.10/dist-packages/ros2_graph/graph_generator.py", line 305, in get_node_graph
    action_clients_data = {
  File "/usr/local/lib/python3.10/dist-packages/ros2_graph/graph_generator.py", line 306, in <dictcomp>
    action: rcu.get_action_related_nodes(action.full_name(), clients=True)
  File "/usr/local/lib/python3.10/dist-packages/ros2_graph/ros_cli_utils.py", line 122, in get_action_related_nodes
    raw_nodes_names = get_clean_lines(
  File "/usr/local/lib/python3.10/dist-packages/ros2_graph/ros_cli_utils.py", line 60, in get_clean_lines
    subprocess.check_output(query_instruction, shell=True)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ros2 action info //simple_move >> actions.txt && sed -n '/Action clients:/, /Action servers:/{ /Action clients:/! { /Action servers:/! p } }' actions.txt | tr -d '[:blank:]' && rm actions.txt' returned non-zero exit status 1.
```

The action topic contains only one "/".

**Comment by charlielito** [comment]
Hi! Thanks for reporting! I was able to reproduce the error. Looking into it
